apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "sematic-server.labels" . | nindent 4 }}
    {{- if .Values.deployment.socket_io.dedicated }}
    app.kubernetes.io/component: api
    {{- else }}
    app.kubernetes.io/component: all
    {{- end }}
spec:
  {{- if not .Values.deployment.autoscaling.enabled }}
  replicas: {{ .Values.deployment.replica_count }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "sematic-server.selectorLabels" . | nindent 6 }}
      {{- if .Values.deployment.socket_io.dedicated }}
      sematic.ai/component: api
      {{- else }}
      sematic.ai/component: all
      {{- end }}
  template:
    metadata:
      {{- with .Values.deployment.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "sematic-server.selectorLabels" . | nindent 8 }}
        {{- if .Values.deployment.socket_io.dedicated }}
        sematic.ai/component: api
        {{- else }}
        sematic.ai/component: all
        {{- end }}
    spec:
      {{- with .Values.image.pull_secrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.service_account.name | default .Release.Name }}
      securityContext:
        {{- toYaml .Values.deployment.security_context | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.deployment.container_security_context | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pull_policy }}
          env:
          - name: SEMATIC_WSGI_WORKERS_COUNT
            value: "{{ .Values.deployment.worker_count }}"
          envFrom:
          - configMapRef:
              name: {{ .Release.Name }}
          - secretRef:
              name: {{ .Release.Name }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.deployment.liveness_probe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.deployment.readiness_probe | nindent 12 }}
          startupProbe:
            {{- toYaml .Values.deployment.startup_probe | nindent 12 }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
      {{- with .Values.deployment.node_selector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
