{{- if .Values.deployment.autoscaling.enabled }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "sematic-server.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}
  minReplicas: {{ .Values.deployment.autoscaling.min_replicas | default 1 }}
  maxReplicas: {{ .Values.deployment.autoscaling.max_replicas | default 1 }}
  metrics:
    {{- if .Values.deployment.autoscaling.target_cpu_utilization_pct }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.deployment.autoscaling.target_cpu_utilization_pct }}
    {{- end }}
    {{- if .Values.deployment.autoscaling.target_memory_utilization_pct }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.deployment.autoscaling.target_memory_utilization_pct }}
    {{- end }}
{{- end }}
