{{ if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "sematic-server.labels" . | nindent 4 }}
data:
  DATABASE_URL: {{ .Values.database.url | b64enc }}
{{ end }}
