{{- if .Values.service_account.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name | default .Release.Name }}
  labels:
    {{- include "sematic-server.labels" . | nindent 4 }}
  {{- with .Values.service_account.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": before-hook-creation
  {{- end }}
{{- end }}
