{{- if .Values.service_account.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.service_account.name | default .Release.Name }}
  labels:
    {{- include "sematic-server.labels" . | nindent 4 }}
  {{- with .Values.service_account.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
