{{- if .Values.service.create }}
{{- if .Values.deployment.socket_io.dedicated }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-socketio
  labels:
    {{- include "sematic-server.labels" . | nindent 4 }}
    app.kubernetes.io/component: socket_io
  annotations:
    {{- toYaml .Values.service.annotations | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "sematic-server.selectorLabels" . | nindent 4 }}
    sematic.ai/component: socket_io
{{- end }}
{{- end }}
