pytest_test(
    name = "test_cluster",
    srcs = ["test_cluster.py"],
    pip_deps = [
        "ray",
    ],
    deps = [
        "//sematic/ee/plugins/external_resource/ray:cluster",
        "//sematic:calculator",
    ],
)