pytest_test(
    name = "test_pipeline",
    srcs = ["test_pipeline.py"],
    deps = [
        "//sematic:init",
        "//sematic/testing:init",
        "//sematic/examples/lightning_resnet:lib",
    ],
    py_versions = [PY3.PY3_9, PY3.PY3_8],
)
