pytest_test(
    name = "test_check",
    srcs = ["test_check.py"],
    deps = [
        "//sematic:abstract_future",
        "//sematic/db/models:git_info",
        "//sematic/db/models:resolution",
        "//sematic/db/models:run",
        "//sematic/db:queries",
        "//sematic/db/tests:fixtures",
        "//sematic/ee/plugins/publishing/github:check",
    ],
)
