#!/bin/bash

# This file allows for entering the python environment
# created by bazel for a Sematic Docker image. You can
# use it like you would any other python interpreter.
# Ex:
# $ bazel_python -c "print('Hello from bazel python')"
# It works by leveraging our worker.py file, which can
# emulate a python interpreter.

if (( $BAZEL_BUILT_IMAGE != 1 )); then
    >&2 echo "This image wasn't built by Bazel in Sematic. bazel_python not available."
    exit 1
fi

# Before we launch the interpreter, we need to make sure
# that it is set up to find the .so files that bazel included
# in the image via nvidia pip dependencies. We have to do this
# dynamically rather than at image build time because the
# bazel image construction mechanisms don't allow us to introspect
# enough on the python target to know the absolute path where
# the libs will be placed. Thus we don't know how to set
# LD_LIBRARY_PATH in advance. It should be noted that doing
# this should negate the need for sematic.torch_patch, BUT
# this hack only happens in cases where we are hacking the
# python interpreter launch to go through this script (e.g.
# for Ray worker images).
CUBLAS_PATH=$(python -c "import os; import glob; print(''.join(glob.glob(os.path.join(os.getcwd(), '../pip_*nvidia_cublas*/site-packages/nvidia/cublas/lib'))))")
CUDNN_PATH=$(python -c "import os; import glob; print(''.join(glob.glob(os.path.join(os.getcwd(), '../pip_*nvidia_cudnn*/site-packages/nvidia/cudnn/lib'))))")
LD_LIBRARY_PATH="$LD_LIBRARY_PATH:$CUBLAS_PATH:$CUDNN_PATH"

# bazel builds the following structure:
# /app/<bazel package of target>/<image target name>.binary
# /app/<bazel package of target>/<image target name>.binary.runfiles/
# and then sets the CWD as a subdirectory of the runfiles dir.
# So to get the binary location, go up two dirs and get the file ending in .binary
WORKER_PY_WRAPPER_PATH=$(python3 -c "from pathlib import Path; import os; print(list(Path(os.getcwd()).parent.parent.glob('*.binary'))[0].as_posix())")

$WORKER_PY_WRAPPER_PATH --emulate-interpreter "$@"
exit $?