pytest_test(
    name = "test_getitem",
    srcs = ["test_getitem.py"],
    deps = [
        "//sematic:future",
        "//sematic/future_operators:getitem",
        "//sematic:calculator",
    ]
)

pytest_test(
    name = "test_iter",
    srcs = ["test_iter.py"],
    deps = [
        "//sematic:future",
        "//sematic:calculator",
        "//sematic/future_operators:iter",
    ]
)