pytest_test(
    name = "test_getitem",
    srcs = ["test_getitem.py"],
    deps = [
        "//sematic:function",
        "//sematic:future",
        "//sematic/future_operators:getitem",
    ],
)

pytest_test(
    name = "test_iter",
    srcs = ["test_iter.py"],
    deps = [
        "//sematic:function",
        "//sematic:future",
        "//sematic/future_operators:iter",
    ],
)
