sematic_example(
    name = "liver_cirrhosis",
    data = ["data/cirrhosis.csv"],
    requirements = [
        "pandas",
        "statsmodels",
        "seaborn",
        "matplotlib",
        "scikit-learn",
        "xgboost",
        "numpy",
    ],
)
