pytest_test(
    name = "test_dataclass",
    srcs = ["test_dataclass.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:init",
    ],
)

pytest_test(
    name = "test_float",
    srcs = ["test_float.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:init",
    ],
)

pytest_test(
    name = "test_float_in_range",
    srcs = ["test_float_in_range.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:generic_type",
        "//sematic/types:init",
        "//sematic/types:serialization",
        "//sematic/types/types:float_in_range",
    ],
)

pytest_test(
    name = "test_integer",
    srcs = ["test_integer.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:init",
        "//sematic/types:serialization",
    ],
)

pytest_test(
    name = "test_list",
    srcs = ["test_list.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:init",
        "//sematic/types:serialization",
    ],
)

pytest_test(
    name = "test_none",
    srcs = ["test_none.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:init",
        "//sematic/types:serialization",
    ],
)

pytest_test(
    name = "test_tuple",
    srcs = ["test_tuple.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:init",
        "//sematic/types:serialization",
    ],
)

pytest_test(
    name = "test_dict",
    srcs = ["test_dict.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:init",
        "//sematic/types:serialization",
    ],
)

pytest_test(
    name = "test_link",
    srcs = ["test_link.py"],
    deps = [
        "//sematic/types/types:link",
    ],
)
