pytest_test(
    name = "test_dataclass",
    srcs = ["test_dataclass.py"],
    deps = [
        "//sematic/types:init",
        "//sematic/types:casting",
    ]
)

pytest_test(
    name = "test_float",
    srcs = ["test_float.py"],
    deps = [
        "//sematic/types:init",
        "//sematic/types:casting",
    ]
)

pytest_test(
    name = "test_float_in_range",
    srcs = ["test_float_in_range.py"],
    deps = [
        "//sematic/types:generic_type",
        "//sematic/types:init",
        "//sematic/types:casting",
        "//sematic/types:serialization",
        "//sematic/types/types:float_in_range",
    ]
)

pytest_test(
    name = "test_integer",
    srcs = ["test_integer.py"],
    deps = [
        "//sematic/types:init",
        "//sematic/types:casting",
        "//sematic/types:serialization",
    ]
)

pytest_test(
    name = "test_list",
    srcs = ["test_list.py"],
    deps = [
        "//sematic/types:init",
        "//sematic/types:casting",
        "//sematic/types:serialization",
    ]
)

pytest_test(
    name = "test_none",
    srcs = ["test_none.py"],
    deps = [
        "//sematic/types:init",
        "//sematic/types:casting",
        "//sematic/types:serialization",
    ]
)