sematic_py_lib(
    name = "abstract_external_resource",
    srcs = ["abstract_external_resource.py"],
    deps = [
        "//sematic:abstract_future",
        "//sematic:future_context",
        "//sematic/utils:exceptions",
    ],
)

sematic_py_lib(
    name = "abstract_kuberay_wrapper",
    srcs = ["abstract_kuberay_wrapper.py"],
    deps = [],
)

sematic_py_lib(
    name = "abstract_storage",
    srcs = ["abstract_storage.py"],
    deps = [
        "//sematic:abstract_plugin",
        "//sematic/config:settings",
        "//sematic/utils:exceptions",
    ],
)

sematic_py_lib(
    name = "abstract_publisher",
    srcs = ["abstract_publisher.py"],
    deps = [],
)
