{
 "title": "Sematic jobs",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "run_id", "label": "Run Id" },
   { "name": "log_filter", "label": "Log Filter" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# Viewing Run\n\n# [$run_id](https://pilot.verdant.sematic.cloud/runs/$run_id)"
   }
  },
  {
   "title": "Job logs",
   "type": "logs",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "expr": "{job=~\".*sematic-worker-$run_id.*\"} |= `` |= `$log_filter` | json line=\"log\" | line_format `{{.line}}`"
    }
   ]
  },
  {
   "title": "Memory Usage Fraction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "avg by(container_name, pod) (container_memory_working_set_bytes{pod=~\".*sematic-worker-$run_id.*\"}) / avg by(container_name, pod) (cluster:namespace:pod_memory:active:kube_pod_container_resource_limits{resource=\"memory\", pod=~\".*sematic-worker-$run_id.*\"})"
    }
   ]
  },
  {
   "title": "Memory Usage GB",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    { "expression": "$A / (1024*1024*1024)", "type": "math" },
    { "expression": "$C / (1024 * 1024 * 1024)", "type": "math" }
   ]
  },
  {
   "title": "Pod CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 21 },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{pod=~\".*sematic-worker-$run_id.*\", container=~\".*sematic-worker-$run_id.*\"}[5m])",
     "legendFormat": "Usage"
    },
    {
     "expr": "avg(cluster:namespace:pod_cpu:active:kube_pod_container_resource_limits{pod=~\".*sematic-worker-$run_id.*\", resource=\"cpu\"})",
     "legendFormat": "Limits"
    }
   ]
  }
 ]
}