sematic_py_lib(
    name = "init",
    srcs = ["__init__.py"],
    pip_deps = [],
    deps = [
        ":mock_funcs",
    ],
)

sematic_py_lib(
    name = "mock_funcs",
    srcs = ["mock_funcs.py"],
    pip_deps = [],
    deps = [
        "//sematic:function",
    ],
)
