pytest_test(
    name = "test_abstract_external_resource",
    srcs = ["test_abstract_external_resource.py"],
    deps = [
        "//sematic:calculator",
        "//sematic/plugins:abstract_external_resource",
        "//sematic/resolvers:silent_resolver",
    ],
)