py_library(
    name = "generic_type",
    srcs = ["generic_type.py"],
    visibility = ["//visibility:public"],
    deps = [
        ":type",
    ]
)

py_library(
    name = "type",
    srcs = ["type.py"],
    visibility = ["//visibility:public"],
)
