pytest_test(
    name = "test_calculator",
    srcs = ["test_calculator.py"],
    deps = [
        "//glow:calculator",
        "//glow:future",
    ]
)

pytest_test(
    name = "test_init",
    srcs = ["test_init.py"],
    deps = [
        "//glow:init",
    ]
)