pytest_test(
    name = "test_calculator",
    srcs = ["test_calculator.py"],
    deps = [
        "//glow:calculator",
        "//glow:future",
        "//glow/types/types:null",
        "//glow/types/types:float",
    ]
)