FROM sematicai/sematic-worker-base:latest
WORKDIR /

RUN apt-get update && apt-get install -y --no-install-recommends apt-utils

RUN python3 -c "import distutils" || apt-get update -y && apt-get install --reinstall -y python$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")-distutils
RUN which pip3 || apt-get update -y && apt-get install -y python3-pip && python3 -m pip install --upgrade pip==23.1.2

ENV PATH="/sematic/bin/:${PATH}"
RUN echo '#!/bin/sh' > entrypoint.sh && echo '/usr/bin/python3 -m sematic.resolvers.worker "$@"' >> entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

COPY sematic/plugins/building/tests/fixtures/requirements.txt requirements.txt
RUN pip3 install --no-cache --ignore-installed -r requirements.txt

COPY sematic/plugins/building/tests/fixtures/docker sematic/plugins/building/tests/fixtures/docker
COPY sematic/plugins/building/tests/fixtures/bad_image_script.sh sematic/plugins/building/tests/fixtures/bad_image_script.sh
COPY sematic/plugins/building/tests/fixtures/good_image_script.sh sematic/plugins/building/tests/fixtures/good_image_script.sh
COPY sematic/plugins/building/tests/fixtures/no_image.yaml sematic/plugins/building/tests/fixtures/no_image.yaml
COPY sematic/plugins/building/tests/fixtures/two_images.yaml sematic/plugins/building/tests/fixtures/two_images.yaml
COPY sematic/plugins/building/tests/fixtures/nested/third_level/third_level.txt sematic/plugins/building/tests/fixtures/nested/third_level/third_level.txt

COPY sematic/plugins/building/tests/fixtures/bad_launch_script.py sematic/plugins/building/tests/fixtures/bad_launch_script.py
COPY sematic/plugins/building/tests/fixtures/good_launch_script.py sematic/plugins/building/tests/fixtures/good_launch_script.py
COPY sematic/plugins/building/tests/fixtures/good_minimal.py sematic/plugins/building/tests/fixtures/good_minimal.py
