FROM sematicai/sematic-worker-base:latest
WORKDIR /

RUN ( echo '#!/bin/sh' > entrypoint.sh && echo '/usr/bin/python3 -m sematic.resolvers.worker "$@"' >> entrypoint.sh && chmod +x /entrypoint.sh )
ENTRYPOINT ["/entrypoint.sh"]

RUN python3 -c "from distutils import cmd, util" || ( apt-get update -y && apt-get install -y --reinstall --no-install-recommends python$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")-distutils )

RUN which pip || ( export PYTHONDONTWRITEBYTECODE=1 && apt-get update -y && apt-get install -y --no-install-recommends wget && wget --no-verbose -O get-pip.py https://bootstrap.pypa.io/get-pip.py && python3 get-pip.py && rm get-pip.py && unset PYTHONDONTWRITEBYTECODE )

COPY sematic/plugins/building/tests/fixtures/docker sematic/plugins/building/tests/fixtures/docker
COPY sematic/plugins/building/tests/fixtures/bad_image_script.sh sematic/plugins/building/tests/fixtures/bad_image_script.sh
COPY sematic/plugins/building/tests/fixtures/good_image_script.sh sematic/plugins/building/tests/fixtures/good_image_script.sh
COPY sematic/plugins/building/tests/fixtures/no_image.yaml sematic/plugins/building/tests/fixtures/no_image.yaml
COPY sematic/plugins/building/tests/fixtures/two_images.yaml sematic/plugins/building/tests/fixtures/two_images.yaml
COPY sematic/plugins/building/tests/fixtures/nested/third_level/third_level.txt sematic/plugins/building/tests/fixtures/nested/third_level/third_level.txt

COPY sematic/plugins/building/tests/fixtures/requirements.txt requirements.txt
RUN pip install --no-cache-dir --ignore-installed --root-user-action=ignore -r requirements.txt

RUN python3 -c "import sematic" || ( export PYTHONDONTWRITEBYTECODE=1 && pip install --no-cache-dir --ignore-installed --root-user-action=ignore sematic cffi && unset PYTHONDONTWRITEBYTECODE )

ENV PATH="/sematic/bin/:$PATH"

COPY sematic/plugins/building/tests/fixtures/bad_launch_script.py sematic/plugins/building/tests/fixtures/bad_launch_script.py
COPY sematic/plugins/building/tests/fixtures/good_launch_script.py sematic/plugins/building/tests/fixtures/good_launch_script.py
COPY sematic/plugins/building/tests/fixtures/good_minimal.py sematic/plugins/building/tests/fixtures/good_minimal.py
