FROM sematicai/sematic-worker-base:latest
WORKDIR /

RUN which pip3 || apt update -y && apt install -y python3-pip
RUN python3 -c "import distutils" || apt update -y && apt install --reinstall -y python$(python3 -c "import sys; print(f'{sys.version_info.major}.{sys.version_info.minor}')")-distutils

ENV PATH="/sematic/bin/:${PATH}"
RUN echo '#!/bin/sh' > entrypoint.sh && echo '/usr/bin/python3 -m sematic.resolvers.worker "$@"' >> entrypoint.sh
RUN chmod +x /entrypoint.sh
ENTRYPOINT ["/entrypoint.sh"]

COPY requirements.txt requirements.txt
RUN pip3 install --no-cache -r requirements.txt

COPY sematic/plugins/building/tests/fixtures/docker sematic/plugins/building/tests/fixtures/docker
COPY sematic/plugins/building/tests/fixtures/bad_image_script.sh sematic/plugins/building/tests/fixtures/bad_image_script.sh
COPY sematic/plugins/building/tests/fixtures/good_image_script.sh sematic/plugins/building/tests/fixtures/good_image_script.sh

COPY sematic/plugins/building/tests/fixtures/__init__.py sematic/plugins/building/tests/fixtures/__init__.py
COPY sematic/plugins/building/tests/fixtures/bad_launch_script.py sematic/plugins/building/tests/fixtures/bad_launch_script.py
COPY sematic/plugins/building/tests/fixtures/good_launch_script.py sematic/plugins/building/tests/fixtures/good_launch_script.py
