pytest_test(
    name = "test_mock_funcs",
    srcs = ["test_mock_funcs.py"],
    deps = [
        "//sematic:abstract_calculator",
        "//sematic:calculator",
        "//sematic/resolvers:silent_resolver",
        "//sematic/testing:mock_funcs",
        "//sematic/utils:exceptions",
    ],
)
