pytest_test(
    name = "test_caching",
    srcs = ["test_caching.py"],
    pip_deps = [],
    deps = [
        "//sematic:abstract_future",
        "//sematic:init",
        "//sematic/caching:caching",
        "//sematic/types:serialization",
    ],
)
