pytest_test(
    name = "test_server_manager",
    srcs = ["test_server_manager.py"],
    deps = [
        "//sematic/plugins/external_resource:timed_message",
        "//sematic/resolvers/resource_managers:server_manager",
    ],
)
