pytest_test(
    name = "test_cloud_manager",
    srcs = ["test_cloud_manager.py"],
    deps = [
        "//sematic/external_resource_plugins:timed_message",
        "//sematic/resolvers/resource_managers:cloud_manager",
    ],
)
