pytest_test(
    name = "test_figure",
    srcs = ["test_figure.py"],
    pip_deps = ["matplotlib"],
    deps = [
        "//sematic/types:init",
        "//sematic/types:serialization",
        "//sematic/types/types:image",
        "//sematic/types/types/matplotlib:figure",
    ],
)
