sematic_example(
    name = "dynamic_graph",  # Replace with name of directory
    requirements = [
        # List your third party dependencies
    ],
    data = [
        # If your example needs local data files (e.g. csv files)
        # list paths relative to this file
    ]
)