sematic_py_lib(
    name = "in_memory_manager",
    srcs = ["in_memory_manager.py"],
    deps = [
        "//sematic/resolvers:abstract_resource_manager",
        "//sematic:external_resource",
    ],
)