# This is the base image for the worker for cloud execution
FROM ubuntu:22.04
#FROM nvidia/cuda:11.7.0-base-ubuntu22.04

ARG DEBIAN_FRONTEND=noninteractive
ENV PATH="/sematic/bin/:${PATH}"

RUN apt update -y
RUN apt install -y software-properties-common
RUN add-apt-repository -y ppa:deadsnakes/ppa
RUN apt install -y python3.9

RUN rm /usr/bin/python3
RUN ln -s /usr/bin/python3.9 /usr/bin/python3
RUN ln -s /usr/bin/python3.9 /usr/bin/python
