sematic_example(
    name = "distilbert",  # Replace with name of directory
    requirements = [
        "numpy",
        "torch",
        "sklearn",
        "transformers",
        "datasets",
    ],
    data = [
        # If your example needs local data files (e.g. csv files)
        # list paths relative to this file
    ]
)