glow_py_lib(
    name = "local_resolver",
    srcs = ["local_resolver.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow:abstract_future",
        "//glow:resolver",
        "//glow:future",
    ]
)