sematic_py_lib(
    name = "dataclass",
    srcs = ["dataclass.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:casting",
        "//sematic/types:serialization",
    ]
)

sematic_py_lib(
    name = "float",
    srcs = ["float.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:serialization",
    ],
)

sematic_py_lib(
    name = "float_in_range",
    srcs = ["float_in_range.py"],
    deps = [
        "//sematic/types:generic_type",
        "//sematic/types:casting",
        "//sematic/types:registry",
        "//sematic/types:type",
        "//sematic/types:serialization",
    ],
)

sematic_py_lib(
    name = "integer",
    srcs = ["integer.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:serialization",
    ],
)


sematic_py_lib(
    name = "list",
    srcs = ["list.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:casting",
        "//sematic/types:serialization",
    ]
)


sematic_py_lib(
    name = "str",
    srcs = ["str.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:serialization",
    ]
)

sematic_py_lib(
    name = "none",
    srcs = ["none.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:serialization",
    ]
)

sematic_py_lib(
    name = "union",
    srcs = ["union.py"],
    deps = [
        "//sematic/types:casting",
        "//sematic/types:registry",
        "//sematic/types:serialization",
    ]
)

sematic_py_lib(
    name = "bool",
    srcs = ["bool.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:serialization",
    ]
)