apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sematic-server-role-binding
  namespace: {{ .Values.namespace }}
subjects:
- kind: ServiceAccount
  name: sematic-sa
  namespace: {{ .Values.namespace }}
roleRef:
  kind: Role
  name: sematic-server-role
  apiGroup: rbac.authorization.k8s.io
