apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: sematic
    app.kubernetes.io/name: generic
  name: sematic-service
  namespace: {{ .Values.namespace }}
spec:
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    app.kubernetes.io/instance: sematic
    app.kubernetes.io/name: generic
  sessionAffinity: None
