pytest_test(
    name = "test_dataset_reference",
    srcs = ["test_dataset_reference.py"],
    deps = [
        "//sematic/types/types/huggingface:dataset_reference",
    ],
)

pytest_test(
    name = "test_model_reference",
    srcs = ["test_model_reference.py"],
    deps = [
        "//sematic/types/types/huggingface:model_reference",
    ],
)

pytest_test(
    name = "test_stored_model",
    srcs = ["test_stored_model.py"],
    deps = [
        "//sematic/types/types/huggingface:stored_model",
    ],
)
