pytest_test(
    name = "test_training_arguments",
    srcs = ["test_training_arguments.py"],
    deps = [
        "//sematic/types:init",
        "//sematic/types:casting",
        "//sematic/types:serialization",
        requirement("transformers"),
    ]
)