pytest_test(
    name = "test_init",
    srcs = ["test_init.py"],
    deps = [
        "//sematic/types:init",
    ]
)

pytest_test(
    name = "test_type",
    srcs = ["test_type.py"],
    deps = [
        "//sematic/types:type",
    ]
)

pytest_test(
    name = "test_casting",
    srcs = ["test_casting.py"],
    deps = [
        "//sematic/types:casting",
    ]
)

pytest_test(
    name = "test_registry",
    srcs = ["test_registry.py"],
    deps = [
        "//sematic/types:registry",
    ]
)

pytest_test(
    name = "test_serialization",
    srcs = ["test_serialization.py"],
    deps = [
        "//sematic/types:serialization",
    ]
)
