sematic_py_lib(
    name = "init",
    srcs = ["__init__.py"],
    deps = [
        "//sematic/ee/plugins/external_resource/ray:cluster",
        "//sematic/plugins:abstract_kuberay_wrapper",
    ],
    pip_deps = [
        "ray",
    ],
)
