
sematic_py_lib(
    name = "ray",
    srcs = ["ray.py"],
    deps = [
        "//sematic/ee/plugins/external_resource/ray:checkpoint",
        "//sematic/ee/plugins/external_resource/ray:cluster",
        "//sematic/plugins:abstract_kuberay_wrapper",
    ],
)
