glow_py_lib(
    name = "float",
    srcs = ["float.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:registry",
        "//glow/types:serialization",
    ],
)

glow_py_lib(
    name = "float_in_range",
    srcs = ["float_in_range.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:generic_type",
        "//glow/types:casting",
        "//glow/types:registry",
        "//glow/types:serialization",
        "//glow/types:type",
    ],
)

glow_py_lib(
    name = "integer",
    srcs = ["integer.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:registry",
        "//glow/types:serialization",
    ],
)


glow_py_lib(
    name = "list",
    srcs = ["list.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:registry",
        "//glow/types:casting",
        "//glow/types:serialization",
    ]
)

glow_py_lib(
    name = "none",
    srcs = ["none.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:registry",
    ],
)