glow_py_lib(
    name = "float",
    srcs = ["float.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:registry",
    ],
)

glow_py_lib(
    name = "float_in_range",
    srcs = ["float_in_range.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:generic_type",
        "//glow/types:casting",
    ],
)

glow_py_lib(
    name = "integer",
    srcs = ["integer.py"],
    visibility = ["//visibility:public"],
    deps = [
        "//glow/types:registry",
    ],
)
