sematic_example(
    name = "hackernews_summarization",
    requirements = [
        "trafilatura",
        "requests",
        "cohere",
        "openai",
    ],
    data = [
        "template.html",
    ],
)
