sematic_example(
    name = "hackernews_summarization",
    requirements=[
        "trafilatura==1.6.0",
        "requests",
        "cohere",
        "sematic",
        "openai",
    ],
    data = [
        "template.html"
    ]
)
