pytest_test(
    name = "test_git",
    srcs = ["test_git.py"],
    deps = [
        "//sematic/utils:git",
    ],
)

pytest_test(
    name = "test_exceptions",
    srcs = ["test_exceptions.py"],
    deps = [
        "//sematic/utils:exceptions",
    ],
)

pytest_test(
    name = "test_stdout",
    srcs = ["test_stdout.py"],
    deps = [
        "//sematic/utils:stdout",
    ],
)

pytest_test(
    name = "test_sorting",
    srcs = ["test_sorting.py"],
    deps = [
        "//sematic/utils:sorting",
    ],
)

pytest_test(
    name = "test_hashing",
    srcs = ["test_hashing.py"],
    deps = [
        "//sematic/types:serialization",
        "//sematic/utils:hashing",
    ],
)
