pytest_test(
    name = "test_make_list",
    srcs = ["test_make_list.py"],
    deps = [
        "//sematic:future",
        "//sematic/resolvers:offline_resolver",
        "//sematic/utils:make_list",
        "//sematic:calculator",
        "//sematic/db/tests:fixtures",
        "//sematic/api/tests:fixtures",
    ]
)