sematic_py_lib(
    name = "docker_builder",
    srcs = ["docker_builder.py"],
    pip_deps = [
        "docker",
        "pyyaml",
    ],
    deps = [
        "//sematic:abstract_plugin",
        "//sematic:container_images",
        "//sematic/plugins:abstract_builder",
    ],
)
