"""empty message

Revision ID: 1be136134246
Revises: 
Create Date: 2023-07-18 14:52:45.901489

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be136134246'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('schema_migrations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schema_migrations',
    sa.Column('version', sa.VARCHAR(length=255), nullable=True),
    sa.PrimaryKeyConstraint('version')
    )
    # ### end Alembic commands ###
