sematic_py_lib(
    name = "image",
    srcs = ["image.py"],
    deps = [
        "//sematic/types:registry",
        "//sematic/types:serialization",
    ]
)

sematic_py_lib(
    name = "init",
    srcs = ["__init__.py"],
    deps = [
        ":image",
    ],
)
