glow_py_lib(
    name = "config_dir",
    srcs = ["config_dir.py"],
    visibility = ["//visibility:public"],
    deps = []
)

glow_py_lib(
    name = "memoized_property",
    srcs = ["memoized_property.py"],
    visibility = ["//visibility:public"],
    deps = []
)