pytest_test(
    name = "test_factories",
    srcs = ["test_factories.py"],
    deps = [
        "//glow:abstract_future",
        "//glow:calculator",
        "//glow/db/models:factories",
    ]
)

pytest_test(
    name = "test_run",
    srcs = ["test_run.py"],
    deps = [
        "//glow:abstract_future",
        "//glow/db/models:run",
    ]
)