pytest_test(
    name = "test_init",
    srcs = ["test_init.py"],
    deps = [
        "//glow/types:init",
    ]
)

pytest_test(
    name = "test_type",
    srcs = ["test_type.py"],
    deps = [
        "//glow/types:type",
    ]
)

pytest_test(
    name = "test_casting",
    srcs = ["test_casting.py"],
    deps = [
        "//glow/types:casting",
    ]
)

pytest_test(
    name = "test_generic",
    srcs = ["test_generic.py"],
    deps = [
        "//glow/types:generic_type",
        "//glow/types:casting",
    ]
)