pytest_test(
    name = "test_init",
    srcs = ["test_init.py"],
    deps = [
        "//glow/types:init",
    ]
)

pytest_test(
    name = "test_type",
    srcs = ["test_type.py"],
    deps = [
        "//glow/types:type",
    ]
)
