pytest_test(
    name = "test_float",
    srcs = ["test_float.py"],
    deps = [
        "//glow/types:init",
        "//glow/types:casting",
    ]
)

pytest_test(
    name = "test_float_in_range",
    srcs = ["test_float_in_range.py"],
    deps = [
        "//glow/types:generic_type",
        "//glow/types:init",
        "//glow/types/types:float_in_range",
    ]
)

pytest_test(
    name = "test_integer",
    srcs = ["test_integer.py"],
    deps = [
        "//glow/types:init",
        "//glow/types:casting",
    ]
)

pytest_test(
    name = "test_list",
    srcs = ["test_list.py"],
    deps = [
        "//glow/types:init",
        "//glow/types:casting",
    ]
)