pytest_test(
    name = "test_standard",
    srcs = ["test_standard.py"],
    deps = [
        "//sematic/plugins:abstract_kuberay_wrapper",
        "//sematic/plugins/kuberay_wrapper:standard",
        "//sematic/utils:env",
        "//sematic/utils:exceptions",
    ],
)