pytest_test(
    name = "test_basic",
    srcs = ["test_basic.py"],
    deps = [
        "//sematic/plugins:abstract_kuberay_wrapper",
        "//sematic/plugins/kuberay_wrapper:basic",
        "//sematic/utils:exceptions",
        "//sematic/tests:fixtures",
    ],
)