pytest_test(
    name = "test_runs",
    srcs = ["test_runs.py"],
    deps = [
        "//glow/api/tests:fixtures",
        "//glow/db/tests:fixtures",
        "//glow/db:queries",
        requirement("flask"),
    ]
)
