pytest_test(
    name = "test_offline_resolver",
    srcs = ["test_offline_resolver.py"],
    deps = [
        "//glow:abstract_future",
        "//glow:calculator",
        "//glow/resolvers:offline_resolver",
        "//glow/types/types:float",
        "//glow/types/types:integer",
    ]
)