pytest_test(
    name = "test_offline_resolver",
    srcs = ["test_offline_resolver.py"],
    deps = [
        "//glow:abstract_future",
        "//glow:calculator",
        "//glow/types:init",
        "//glow/db/tests:fixtures",
        "//glow/resolvers:offline_resolver",
    ]
)