sematic_py_lib(
    name = "standard",
    srcs = ["standard.py"],
    deps = [
        "//sematic:abstract_plugin",
        "//sematic/config:settings",
        "//sematic/plugins:abstract_kuberay_wrapper",
        "//sematic/utils:exceptions",
    ],
)