pytest_test(
    name = "test_snowflake_table",
    srcs = ["test_snowflake_table.py"],
    deps = [
        "//sematic/types/types/snowflake:snowflake_table",
        requirement("pandas"),
        requirement("pyarrow"),
        requirement("snowflake-connector-python"),
    ]
)