pytest_test(
    name = "test_snowflake_table",
    srcs = ["test_snowflake_table.py"],
    deps = [
        "//sematic/types/types/snowflake:snowflake_table",
    ],
    pip_deps = [
        "pandas",
        "pyarrow",
        "snowflake-connector-python",
    ],
)