pytest_test(
    name = "test_metrics",
    srcs = ["test_metrics.py"],
    deps = [
        "//sematic:future_context",
        "//sematic/ee:metrics",
        "//sematic/metrics:metric_point",
        "//sematic/utils:exceptions",
    ],
)
